### PR TITLE
Db branch-  CRUD OPERATIONS

### LINKED ISSUE #6: [db-branch] CRUD operations.
Will create basic crud operations for the same model

### PR DESCRIPTION
**Pull request by Vanshika-73**
I have created all crud operations, currently you won't be able to test these because routes are left to be coded. As per this issue, i have just added functions. Will soon add routes with next issue linked.
Closes #6

### CODE REVIEW

**Comment by LuciAkirami** [comment]
Great work. Small changes required. 
- Provide comments where ever required for readability
- Error spelling wrong in res.send()

**Comment by Vanshika-73** [comment]
changes done.

**Comment by LuciAkirami** [comment]
The error spelling is still not corrected

**Comment by Vanshika-73** [comment]
Have a look now please!

**Comment by LuciAkirami** [comment]
Cool, merging the changes

**Pull request merged**
