### PR TITLE
data insertion

### LINKED ISSUE #5: [db-branch] function to add sample data to db.
Will create basic simple function to add data that will be called only once. (require MongoUrl for it).

### PR DESCRIPTION
**Pull request by Vanshika-73**
created a single function to insert data for demo. closes #5

### CODE REVIEW

**Comment by Vanshika-73** [comment]
Screenshot (172)

**Comment by LuciAkirami** [comment]
Coool. Can you once go through the execution steps of adding in the data???, so that I can reproduce the results from my end

**Comment by Vanshika-73** [comment]
Sorry, I didn't get you!! Can you repeat it in more detail?

**Comment by LuciAkirami** [comment]
I want to reproduce the results of adding the data to the database. I mean do I just run the server.js(also setting the Mongo URI) and the data get in my MongoDB? or do I have to run the other files first to get the data injected to the MongoDB?

**Comment by Vanshika-73** [comment]
No just run server once, if you will run twice, data will too get inserted
twice.
Set Mongo url in connect_dB.js

**Comment by LuciAkirami** [comment]
I get an error saying
```
connect_db(); //enter your url in this file
^

ReferenceError: connect_db is not defined
```

-> Solution: Fix the import in `insertData.js`. The connect_db was not imported in this file. Hence the error

**Comment by Vanshika-73** [comment]
have you entered your Mongo url? after running "npm i" command

**Comment by LuciAkirami** [comment]
> have you entered your Mongo url? after running "npm i" command

Yup, the error is with respect to the `insertData.js`
-> Solution: Fix the import in insertData.js. The connect_db was not imported in this file. Hence the error

**Comment by Vanshika-73** [comment]
removed that code of line, there was no requirement of that!

**Comment by LuciAkirami** [comment]
Cool, it's working fine now. Merging this commit

**Pull request merged**
